### ISSUE TITLE
One-Time connect() does not work

### ISSUE THREAD

**Issue by Magnati** [nayan32biswas/mongodb-odm#32]
python: 3.11
    fastapi==0.110.0
    mongodb-odm==1.0.0
    pydantic==2.6.4
    pydantic_core==2.16.3
    pymongo==4.6.2
    uvicorn==0.28.0

---

Hey! 

I have problems creating a functional connection between my FastAPI app and my mongodb.

The docs state that calling one time
```python
connect(os.environ.get("MONGO_URL", "mongodb://localhost:27017/test"))
```
is sufficient.

In my case I have a MONGO_URL with user:password credentials: `mongodb://<user>:<pw>@localhost:27017/<db_name>` .
But when later on I want to fetch some data or create a new entry (as in the example code below) I get an authentication error.

```bash
/path/to/repo/venv/bin/python /path/to/repo/mongodb-odm/test_main.py 
Traceback (most recent call last):
  File "/path/to/repo/mongodb-odm/test_main.py", line 71, in <module>
    ).create()
      ^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/mongodb_odm/models.py", line 277, in create
    inserted_id = _collection.insert_one(data, **kwargs).inserted_id
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/collection.py", line 669, in insert_one
    self._insert_one(
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 2416, in _write
    with self._client._checkout(self._server, self._session) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1252, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1637, in checkout
    conn = self._get_conn(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1756, in _get_conn
    conn = self.connect(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1607, in connect
    conn.authenticate()
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/pool.py", line 1078, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/auth.py", line 625, in authenticate
    auth_func(credentials, conn)
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/auth.py", line 530, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/auth.py", line 257, in _authenticate_scram
    res = conn.command(source, cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 322, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/pool.py", line 968, in command
    return command(
           ^^^^^^^^
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/network.py", line 192, in command
    helpers._check_command_response(
  File "/path/to/repo/venv/lib/python3.11/site-packages/pymongo/helpers.py", line 230, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

Process finished with exit code 1
```

Here my adapted minimal example:
```python
import os
from typing import Optional

import uvicorn
from bson import ObjectId
from dotenv import load_dotenv
from fastapi import FastAPI, status, APIRouter
from mongodb_odm import Document, connect


load_dotenv(".env")  # for correct MONGO_URL

# model schemas
class StarfleetShip(Document):
    name: str
    registry: str
    phaser: int
    torpedo_launcher: int

    class ODMConfig(Document.ODMConfig):
        allow_inheritance = True


class StarfleetShipExtend(StarfleetShip):
    captain_name: Optional[str] = None
    warp_std: Optional[float] = None
    warp_max: Optional[float] = None

    class ODMConfig(Document.ODMConfig):
        allow_inheritance = False
        collection_name = "starfleet_ship"

# ---

connect(os.environ.get("MONGO_URL", "mongodb://localhost:27017/testdb"))

app = FastAPI()
app.title = 'MongoDB-ODM Test Service'

router = APIRouter(
    prefix='/starfleet',
    tags=['starfleet'],
    responses={status.HTTP_404_NOT_FOUND: {"description": "Not Found"}}
)

@router.get('/ship',
            status_code=status.HTTP_200_OK,
            #response_model=list[StarfleetShipExtend],
            )
def get_ships():
    """Get all ships."""
    return list(StarfleetShipExtend.find())


@router.get('/ship/{object-id}', status_code=status.HTTP_200_OK)
def get_ship_detail(object_id: str):# -> StarfleetShipExtend:
    """Get one ship."""
    return StarfleetShipExtend.find_one({'_id': ObjectId(object_id)})


app.include_router(router)

StarfleetShipExtend(
    name="USS Enterprise",
    registry="NCC-1701",
    phaser=8,
    torpedo_launcher=2,
    captain_name="James T. Kirk",
    warp_std=6.0,
    warp_max=9.6
).create()

def main():
    uvicorn.run('main:app', host="0.0.0.0", port=4567)

if __name__ == '__main__':
    main()

```

**Comment by nayan32biswas** [comment]
Hi @Magnati, it's looks like your database connection is authenticated properly (`pymongo.errors.OperationFailure: Authentication failed.`).
I have tried out same functionality and it's working fine.
Could you try it again?
